### ISSUE TITLE
 linux musl Nuget packages cannot work

### ISSUE THREAD

**Issue by w8tcha** [Vampire2008/Citizen17.DartSass#2]
The dart sass runtime files are not copied to the output path. Because of the missing props file inside the package. This is caused because the wrong names inside the proj files.

Fixed in 
https://github.com/Vampire2008/Citizen17.DartSass/pull/1

**Comment by Vampire2008** [comment]
Hello! Thank you for fixing! I have merged the PR. I have published fix in 1.75.0.1 version. It will be listed in Nuget soon.
